apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverse-proxy
  name: udagram-reverse-proxy-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service: udagram-reverse-proxy
